### ISSUE TITLE
How to get train/valid/test.csv?

### ISSUE THREAD

**Issue by VanillaCreamer** [REASONER2023/reasoner2023.github.io#1]
There are requiements file in tag_predict.py and review_generate.py, like test.csv.

However, there is no code in your project to obtain them. And the source dataset are not split.

Therefore, could you tell me how to obtain the train/valid/test.csv files?

Appreciate it a lot.

**Comment by JingsenZhang** [comment]
Thank you for following our project~
We randomly split the interaction records of each user into training, validation, and test sets according to the ratio of 8:1:1. And we add the link of divided dataset at the part of Quick Start in README.md.
You can also divide it according to your needs.

**Comment by VanillaCreamer** [comment]
It was so awesome of you.
