### ISSUE TITLE
How to convert the answer values in bigfive.csv to OCEAN values?

### ISSUE THREAD

**Issue by WeixinChen98** [REASONER2023/reasoner2023.github.io#2]
Thanks for this valuable dataset!

Since the questions' indices and descriptions shown in the readme file are not directly consistent with that in [Big Five Personality Test](https://www.psytoolkit.org/survey-library/big5-bfi-s.html), I may not get the OCEAN values of each user directly from the bigfive.csv file.

For example, the value of **O**penness should be the mean of Q3, Q4, and Q10 in this dataset (I think), while it should be the mean of Q7, Q8 and Q9 in [Big Five Personality Test](https://www.psytoolkit.org/survey-library/big5-bfi-s.html).

Could you please indicate how to convert the answer values in bigfive.csv to OCEAN values or map the questions' indices in this dataset to that in [Big Five Personality Test](https://www.psytoolkit.org/survey-library/big5-bfi-s.html)?

**Comment by REASONER2023** [comment]
Thanks for your interest in our dataset.  Our dataset is actually more
consistent with this survey
https://www.xinlixue.cn/web/xinliliangbiao/rengeliangbiao/2020-04-01/849.html.
However, this link is Chinese, thus we refer the users to Big Five
Personality Test <https://www.psytoolkit.org/survey-library/big5-bfi-s.html>
for wider audience.  I think you can easily draw a mapping between
https://www.xinlixue.cn/web/xinliliangbiao/rengeliangbiao/2020-04-01/849.html
and Big Five Personality Test
<https://www.psytoolkit.org/survey-library/big5-bfi-s.html> .


PS: from
https://www.xinlixue.cn/web/xinliliangbiao/rengeliangbiao/2020-04-01/849.html,
you can see:

"
CBF-PI-15量表采用李克特六点计分，1代表完全不符合，2代表大部分不符合，3代表有点不符合，4代表有点符合，5代表大部分符合，6代表完全符合，其中，第2和第5题反向计分。7，11，12属于神经质维度；6，8，15属于尽责性维度；1，9，13属于宜人性维度；3，4，10属于开放性维度；2，5，14属于外向性维度.
"

Reference: Zhang, X., Wang, M-C, Luo, J., He, L. (under review). The
development and psychometrics evaluation of a very shorten version of the
Chinese Big five personality inventory. PLoS ONE.



Weixin Chen ***@***.***> 于2023年6月18日周日 18:16写道：

**Comment by WeixinChen98** [comment]
Thanks for your explanation!
