### ISSUE TITLE
Enquiry on the Sequentiality of Interaction Records in interactions.csv

### ISSUE THREAD

**Issue by WeixinChen98** [REASONER2023/reasoner2023.github.io#3]
I would like to know the sequentiality of interaction records in the interactions.csv file. Specifically, I want to know if the interaction records are sequential by default or if there is a timestamp label available to indicate the order of interactions.

As the relative order of a user's interacted items is essential for sequential recommendation, it would be helpful to know if the dataset provides this information.

Thank you for your time and assistance.

**Comment by JingsenZhang** [comment]
Hi~
Thanks for your attention to REASOER dataset. 
Unfortunately, there is no sequence of interaction records in the dataset.

**Comment by JingsenZhang** [comment]
Hi~
Thanks for your attention to REASOER dataset.
Unfortunately, there is no sequence of interaction records in the dataset. A user's interaction records are generated by randomly recommended and human annotated.

**Comment by WeixinChen98** [comment]
Thanks for your explanation! @JingsenZhang
