### ISSUE TITLE
Trainer.evaluate use data.positive_video_tag in evaluate_ndcg when evaluating reason_ndcg and interest ndcg.

### ISSUE THREAD

**Issue by juyaoliu** [REASONER2023/reasoner2023.github.io#6]
Trainer.evaluate use data.positive_video_tag in evaluate_ndcg when evaluating reason_ndcg and interest ndcg.
```python
# reason_tag
reason_p, reason_r, reason_f1 = evaluate_precision_recall_f1(self.top_k, data.positive_reason_tag,
                                                             reason_predict)
reason_ndcg = evaluate_ndcg(self.top_k, data.positive_video_tag, reason_predict)
# video_tag
video_p, video_r, video_f1 = evaluate_precision_recall_f1(self.top_k, data.positive_video_tag, video_predict)
video_ndcg = evaluate_ndcg(self.top_k, data.positive_video_tag, video_predict)
# interest_tag
interest_p, interest_r, interest_f1 = evaluate_precision_recall_f1(self.top_k, data.positive_interest_tag,
                                                                   interest_predict)
interest_ndcg = evaluate_ndcg(self.top_k, data.positive_video_tag, interest_predict)
```

**Comment by JingsenZhang** [comment]
Hello, thank you for paying attention to our project, please state your question in detail.

**Comment by juyaoliu** [comment]
I mean, there might be some errors. When evaluating the NDCG of reason_predict and interest_predict, the comparison should be made with data.positive_reason_tag and data.positive_interest_tag, respectively. However, this code uses data.positive_video_tag as the ground truth.

**Comment by JingsenZhang** [comment]
You are correct, this is my negligence, and I will make corrections. Thank you.

---- Replied Message ----
From juyaoliu ***@***.***> Date 11/15/2023 17:45 To ***@***.***> Cc Jingsen Zhang ***@***.***>,
Comment ***@***.***> Subject Re: [REASONER2023/reasoner2023.github.io] Trainer.evaluate use data.positive_video_tag in evaluate_ndcg when evaluating reason_ndcg and interest ndcg. (Issue #6)  

I mean, there might be some errors. When evaluating the NDCG of reason_predict and interest_predict, the comparison should be made with data.positive_reason_tag and data.positive_interest_tag, respectively. However, this code uses data.positive_video_tag as the ground truth.
