### ISSUE TITLE
Why does the code generate negative tags by randomly selecting from all available tags?

### ISSUE THREAD

**Issue by juyaoliu** [REASONER2023/reasoner2023.github.io#7]
Each video comes with its set of tags, and I believe relevant tags that a user provides for a video are selected from this set. Why does the code generate negative tags by randomly selecting from all available tags, rather than utilizing the video tags that the user finds uninteresting?

Here are relevant codes in data.batchify.py:
```python
def get_candidate_tags(self, pos_tag_list, candidate_num):
    neg_tag_num = candidate_num - len(pos_tag_list)
    candi_tag_list = [i for i in pos_tag_list]
    for i in range(neg_tag_num):
        neg_tag = np.random.randint(self.tag_num)
        while neg_tag in pos_tag_list:
            neg_tag = np.random.randint(self.tag_num)
        candi_tag_list.append(neg_tag)
    random.shuffle(candi_tag_list)
    return candi_tag_list
```

**Comment by JingsenZhang** [comment]
Hello, thank you for following our project.
I believe your approach is also reasonable, as long as you can ensure that no positive samples are selected.
