### ISSUE TITLE
YAML configuration file example

### ISSUE THREAD

**Issue by Xiaoyu-SZ** [REASONER2023/reasoner2023.github.io#8]
Thanks for creating and sharing this wonderful repository.
I noticed that running the provided explainable recommendation model code requires corresponding yaml files. Would it be possible for you to provide an example yaml as a reference? It would be tremendously helpful. Thank you.

**Comment by JingsenZhang** [comment]
Hi Xiaoyu,
Thanks for your attention to our REASONER dataset. The config files(.yaml) have been provided in the folder of named **_properties_**.
