### ISSUE TITLE
Time Sequencing of Interactions in interaction.csv

### ISSUE THREAD

**Issue by Xiaoyu-SZ** [REASONER2023/reasoner2023.github.io#9]
I have been working with the data and I have a question regarding the time sequencing of interactions in the "interaction.csv" file. I would like to inquire whether there is a time sequence between interactions for each user in the .csv file, meaning **for the same user**, as shown in the figure, the interactions listed later in the file also occur later in the time series. 

<img width="207" alt="image" src="https://github.com/REASONER2023/reasoner2023.github.io/assets/48305798/1e7c5763-43ca-4b8d-ac07-cc70c0a7dd35">

I have noticed a similar discussion in Issue [#3](https://github.com/REASONER2023/reasoner2023.github.io/issues/3#issue-1805915930). There is a mention of "A user's interaction records are generated by randomly recommended." I want to ensure whether it implies that the order of records for the same user in the "interaction.csv" file is randomized.

Thank you for your time.

**Comment by Xiaoyu-SZ** [comment]
Also, I would like to know if it is possible to get the mapping between the features indicated by IDs and their values or meanings, such as occupation, education level, etc.

**Comment by JingsenZhang** [comment]
Hello Xiaoyu-SZ,
Thanks for your attention to our REASONER dataset. 
1.  The order of records for the same user in the "interaction.csv" file is random.
2. For the mapping files, please send email to "reasonerdataset@gmail.com" for acquisition.
